variables:
- name: Version1
  value: 0.0.0-$(Date:yyyyMMdd).$(Rev:r)
- group: FeedSettings

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo AccountFeed $(AccountFeed)
- script: echo Version $(Version)
- script: echo Version1 $(Version1)
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: '$(AccountFeed)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    arguments: '-p:Version=$(Version1)'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    nobuild: true

- task: DotNetCoreCLI@2
  displayName: Push
  inputs:
    command: push
    publishVstsFeed: '$(AccountFeed)'
