name: Build Dependencies

on:
  package:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger build of Xtate.Serialization
      uses: octokit/request-action@v2.0.2
      with:
        route: POST repos/TSSArt/Xtate.Serialization/actions/workflows/publish.yml/dispatches
