name: Build Dependencies

on:
  registry_package:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.BOT_ACTION_TOKEN }}

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - uses: octokit/request-action@v2.0.2
      with: 
        route: POST repos/TSSArt/Xtate.Serialization/actions/workflows/publish.yml/dispatches
        ref: master
