name: Build Dependencies

on:
  registry_package:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.BOT_ACTION_TOKEN }}

jobs:
  trigger:
    name: Trigger Publish of ${{ matrix.repo }}
    strategy:
      matrix:
        repo: 
          - TSSArt/Xtate
          - TSSArt/Xtate.Serialization
          - TSSArt/Xtate.DataModel.EcmaScript
          - TSSArt/Xtate.IoProcessor.Http
          - TSSArt/Xtate.Service.HttpClient
          - TSSArt/Xtate.Service.SmtpClient
          - TSSArt/Xtate.Logger.Serilog
    
    runs-on: ubuntu-latest
  
    steps:
      - name: Workflow Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish.yml
          token: ${{ secrets.BOT_ACTION_TOKEN }}
          repo: ${{ matrix.repo }}
          ref: master
